name: MSO_E5_Dev_AutoRenew

on: 
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  schedule:
    - cron: "10 */2 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event.repository.owner.id == github.event.sender.id) || ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: Build and call API
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          check-latest: true
      
      - name: Install requests
        run: pip install requests
      
      - name: Read config from secrets
        env: 
          CONFIG_ID: ${{ secrets.CONFIG_ID }}
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          cp helpers.py temp.py
          sed -i "s|CONFIG_ID_PLACEHOLDER|$CONFIG_ID|" temp.py
          sed -i "s|CONFIG_KEY_PLACEHOLDER|$CONFIG_KEY|" temp.py
          sed -i "s|REFRESH_TOKEN_PLACEHOLDER|$REFRESH_TOKEN|" temp.py
      
      - name: Test API
        run: | 
          echo "$(date +"%Y-%m-%d %H:%M:%S") begin" > time.log
          python3 temp.py
      
      - name: Delete secrets config
        run: rm -f temp.py
      
      - name: Commit changes
        run: |
          git config --global user.email "kjmcabangon@slsu.edu.ph"
          git config --global user.name "kylierst"
          git add .
          git commit -m "Update refresh token with MSO_E5_Dev_AutoRenew" -a || echo "No changes to commit"
      
      - name: Push changes
        if: github.ref != 'refs/heads/master' # Avoid pushing invalid refs
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Pull changes (optional)
        run: git pull origin ${{ github.ref }} || echo "No changes in remote to pull"
